SET DATAZILLA_DATABASE_HOST=10.242.24.64
SET DATAZILLA_DATABASE_PORT=3306
SET DATAZILLA_DATABASE_NAME=datazilla
SET DATAZILLA_DATABASE_USER=root
SET DATAZILLA_DATABASE_PASSWORD=manager
SET DATAZILLA_RO_DATABASE_USER=root
SET DATAZILLA_RO_DATABASE_PASSWORD=manager
SET DATAZILLA_DEBUG=true

python manage.py update_pushlog --repo_host=hg.mozilla.org --hours=24